services:
  - type: web
    name: location-express-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    rootDir: backend-vehicules
    plan: free
    region: frankfurt
    envVars:
      - key: APP_NAME
        value: Location Express
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_PORT
        value: 4000
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt
      - key: MYSQL_ATTR_SSL_VERIFY_SERVER_CERT
        value: false
